export const paths = {
  PROFILE: "profile/list",
  PROFILEFORM: "profile/form",
  CUSTOMER: "customer/list",
  CUSTOMERFORM: "customer/form",
  ROLES: "roles/list",
  ROLESFORM: "roles/form",
  MYUSER: "myUser/list",
  MYUSERFORM: "/myUser/form",
  PARAM: "parameters",
  LOGIN: "/",
  MENU: "/menu",
  HOME: "/home/*",
  PRODUCTMASTER: "productMaster/list",
  PRODUCTMASTERFORM: "productMaster/form",
  MENUMASTER: "menuMaster/list",
  MENUMASTERFORM: "menuMaster/form",
  FORMMASTER: "formMaster/list",
  FORMMASTERFORM: "formMaster/form",
};
