export const mapPaths = {
    PROFILE: "profile/list",
    PROFILEFORM: "profile/form",
    CUSTOMER: "customer/list",
    CUSTOMERFORM: "customer/form",
    ROLES: "roles/list",
    ROLESFORM: "roles/form",
    MYUSER: "myUser/list",
    MYUSERFORM: "myUser/form",
    PARAM: "parameters",
    LOGIN: "/",
    MENU: "/menu",
    HOME:'/home/*',
    PRODUCTMASTER: "productMaster/list",
    PRODUCTMASTERFORM: "productMaster/form",
    MENUMASTER: "menuMaster/list",
    MENUMASTERFORM: "menuMaster/form",
    FORMMASTER: "formMaster/list",
    FORMMASTERFORM: "formMaster/form",
  };

  export const clickPaths = {
    USENAVIGATEHOME:'/home/productMaster/list',
    USENAVIGATEMYUSER:'/home/myUser/form',
    USENAVIGATEMYUSERFORM:'/home/myUser/list',
    USENAVIGATEPRODUCTMASTERFORM: "/home/productMaster/form",
    USENAVIGATEMENUMASTER: "/home/menuMaster/list",
    USENAVIGATEMENUMASTERFORM: "/home/menuMaster/form",
    USENAVIGATEFORMMASTER: "/home/formMaster/list",
    USENAVIGATEFORMMASTERFORM: "/home/formMaster/form",
    USENAVIGATEPROFILE: "/home/profile/list",
    USENAVIGATEPROFILEFORM: "/home/profile/form",
    USENAVIGATECUSTOMER: "/home/customer/list",
    USENAVIGATECUSTOMERFORM: "/home/customer/form",
    USENAVIGATEROLES: "/home/roles/list",
    USENAVIGATEROLESFORM: "/home/roles/form",
    USENAVIGATEPARAM: "/home/parameters",
  }